/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnsweredRouteImport } from './routes/answered'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as CareAgreementRouteImport } from './routes/care-agreement'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CounselorsRouteImport } from './routes/counselors'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as GivingRouteImport } from './routes/giving'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HireRouteImport } from './routes/hire'
import { Route as HoursRouteImport } from './routes/hours'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KindnessRouteImport } from './routes/kindness'
import { Route as LanesRouteImport } from './routes/lanes'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as NeedsRouteImport } from './routes/needs'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PerksRouteImport } from './routes/perks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoomRouteImport } from './routes/room'
import { Route as ServeRouteImport } from './routes/serve'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpotlightRouteImport } from './routes/spotlight'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TherapyRouteImport } from './routes/therapy'
import { Route as TourRouteImport } from './routes/tour'
import { Route as WalkRouteImport } from './routes/walk'
import { Route as WallRouteImport } from './routes/wall'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminCounselorsRouteImport } from './routes/admin.counselors'
import { Route as AdminGiftsRouteImport } from './routes/admin.gifts'
import { Route as AdminGrantsRouteImport } from './routes/admin.grants'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminProsRouteImport } from './routes/admin.pros'
import { Route as AdminSuggestionsRouteImport } from './routes/admin.suggestions'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as BadgeIdRouteImport } from './routes/badge.$id'
import { Route as CallIdRouteImport } from './routes/call.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as CommunityChurchesRouteImport } from './routes/community.churches'
import { Route as CommunityNewRouteImport } from './routes/community.new'
import { Route as CounselorSlugRouteImport } from './routes/counselor.$slug'
import { Route as CounselorsIndexRouteImport } from './routes/counselors.index'
import { Route as CounselorsMineRouteImport } from './routes/counselors.mine'
import { Route as CounselorsNewRouteImport } from './routes/counselors.new'
import { Route as DonateSlugRouteImport } from './routes/donate.$slug'
import { Route as FilmIdRouteImport } from './routes/film.$id'
import { Route as FilmQueueRouteImport } from './routes/film.queue'
import { Route as GivingIndexRouteImport } from './routes/giving.index'
import { Route as GivingLaneRouteImport } from './routes/giving.$lane'
import { Route as GivingFundRouteImport } from './routes/giving.fund'
import { Route as GivingNonprofitsRouteImport } from './routes/giving.nonprofits'
import { Route as GivingWitnessRouteImport } from './routes/giving.witness'
import { Route as GratitudeIndexRouteImport } from './routes/gratitude.index'
import { Route as GratitudeIdRouteImport } from './routes/gratitude.$id'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as JourneyIdRouteImport } from './routes/journey.$id'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as NeedsIndexRouteImport } from './routes/needs.index'
import { Route as NeedsIdRouteImport } from './routes/needs.$id'
import { Route as NeedsNewRouteImport } from './routes/needs.new'
import { Route as NeedsStoriesRouteImport } from './routes/needs.stories'
import { Route as PersonIdRouteImport } from './routes/person.$id'
import { Route as PrayerIdRouteImport } from './routes/prayer.$id'
import { Route as ProSlugRouteImport } from './routes/pro.$slug'
import { Route as ProsIndexRouteImport } from './routes/pros.index'
import { Route as ProsLeadsRouteImport } from './routes/pros.leads'
import { Route as ProsMineRouteImport } from './routes/pros.mine'
import { Route as ProsNewRouteImport } from './routes/pros.new'
import { Route as ProsPaymentsRouteImport } from './routes/pros.payments'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as SitIdRouteImport } from './routes/sit.$id'
import { Route as SpacesOrganizationRouteImport } from './routes/spaces.organization'
import { Route as SpacesProfessionalRouteImport } from './routes/spaces.professional'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as TestimonialsShareRouteImport } from './routes/testimonials.share'
import { Route as TherapyIndexRouteImport } from './routes/therapy.index'
import { Route as TherapyIdRouteImport } from './routes/therapy.$id'
import { Route as WalkIndexRouteImport } from './routes/walk.index'
import { Route as WalkIdRouteImport } from './routes/walk.$id'
import { Route as CommunityClaimSlugRouteImport } from './routes/community.claim.$slug'
import { Route as CommunityDashboardSlugRouteImport } from './routes/community.dashboard.$slug'
import { Route as CommunityManageSlugRouteImport } from './routes/community.manage.$slug'
import { Route as CommunityPaymentsSlugRouteImport } from './routes/community.payments.$slug'
import { Route as CommunityProfileSlugRouteImport } from './routes/community.profile.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPayoutsRunRouteImport } from './routes/api/public/payouts.run'
import { Route as ApiPublicPushRemindersRouteImport } from './routes/api/public/push.reminders'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsweredRoute = AnsweredRouteImport.update({
  id: '/answered',
  path: '/answered',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CareAgreementRoute = CareAgreementRouteImport.update({
  id: '/care-agreement',
  path: '/care-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorsRoute = CounselorsRouteImport.update({
  id: '/counselors',
  path: '/counselors',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingRoute = GivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursRoute = HoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KindnessRoute = KindnessRouteImport.update({
  id: '/kindness',
  path: '/kindness',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesRoute = LanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRoute = NeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PerksRoute = PerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeRoute = ServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightRoute = SpotlightRouteImport.update({
  id: '/spotlight',
  path: '/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapyRoute = TherapyRouteImport.update({
  id: '/therapy',
  path: '/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCounselorsRoute = AdminCounselorsRouteImport.update({
  id: '/admin/counselors',
  path: '/admin/counselors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGiftsRoute = AdminGiftsRouteImport.update({
  id: '/admin/gifts',
  path: '/admin/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGrantsRoute = AdminGrantsRouteImport.update({
  id: '/admin/grants',
  path: '/admin/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProsRoute = AdminProsRouteImport.update({
  id: '/admin/pros',
  path: '/admin/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuggestionsRoute = AdminSuggestionsRouteImport.update({
  id: '/admin/suggestions',
  path: '/admin/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeIdRoute = BadgeIdRouteImport.update({
  id: '/badge/$id',
  path: '/badge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIdRoute = CallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityChurchesRoute = CommunityChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityNewRoute = CommunityNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CommunityRoute,
} as any)
const CounselorSlugRoute = CounselorSlugRouteImport.update({
  id: '/counselor/$slug',
  path: '/counselor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorsIndexRoute = CounselorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CounselorsRoute,
} as any)
const CounselorsMineRoute = CounselorsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => CounselorsRoute,
} as any)
const CounselorsNewRoute = CounselorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CounselorsRoute,
} as any)
const DonateSlugRoute = DonateSlugRouteImport.update({
  id: '/donate/$slug',
  path: '/donate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmQueueRoute = FilmQueueRouteImport.update({
  id: '/film/queue',
  path: '/film/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const GivingIndexRoute = GivingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GivingRoute,
} as any)
const GivingLaneRoute = GivingLaneRouteImport.update({
  id: '/$lane',
  path: '/$lane',
  getParentRoute: () => GivingRoute,
} as any)
const GivingFundRoute = GivingFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => GivingRoute,
} as any)
const GivingNonprofitsRoute = GivingNonprofitsRouteImport.update({
  id: '/nonprofits',
  path: '/nonprofits',
  getParentRoute: () => GivingRoute,
} as any)
const GivingWitnessRoute = GivingWitnessRouteImport.update({
  id: '/witness',
  path: '/witness',
  getParentRoute: () => GivingRoute,
} as any)
const GratitudeIndexRoute = GratitudeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GratitudeRoute,
} as any)
const GratitudeIdRoute = GratitudeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GratitudeRoute,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIdRoute = JourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsIndexRoute = NeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeedsRoute,
} as any)
const NeedsIdRoute = NeedsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NeedsRoute,
} as any)
const NeedsNewRoute = NeedsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NeedsRoute,
} as any)
const NeedsStoriesRoute = NeedsStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => NeedsRoute,
} as any)
const PersonIdRoute = PersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerIdRoute = PrayerIdRouteImport.update({
  id: '/prayer/$id',
  path: '/prayer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSlugRoute = ProSlugRouteImport.update({
  id: '/pro/$slug',
  path: '/pro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsIndexRoute = ProsIndexRouteImport.update({
  id: '/pros/',
  path: '/pros/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsLeadsRoute = ProsLeadsRouteImport.update({
  id: '/pros/leads',
  path: '/pros/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsMineRoute = ProsMineRouteImport.update({
  id: '/pros/mine',
  path: '/pros/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsNewRoute = ProsNewRouteImport.update({
  id: '/pros/new',
  path: '/pros/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsPaymentsRoute = ProsPaymentsRouteImport.update({
  id: '/pros/payments',
  path: '/pros/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SitIdRoute = SitIdRouteImport.update({
  id: '/sit/$id',
  path: '/sit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesOrganizationRoute = SpacesOrganizationRouteImport.update({
  id: '/spaces/organization',
  path: '/spaces/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesProfessionalRoute = SpacesProfessionalRouteImport.update({
  id: '/spaces/professional',
  path: '/spaces/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsShareRoute = TestimonialsShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => TestimonialsRoute,
} as any)
const TherapyIndexRoute = TherapyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TherapyRoute,
} as any)
const TherapyIdRoute = TherapyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TherapyRoute,
} as any)
const WalkIndexRoute = WalkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalkRoute,
} as any)
const WalkIdRoute = WalkIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WalkRoute,
} as any)
const CommunityClaimSlugRoute = CommunityClaimSlugRouteImport.update({
  id: '/claim/$slug',
  path: '/claim/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityDashboardSlugRoute = CommunityDashboardSlugRouteImport.update({
  id: '/dashboard/$slug',
  path: '/dashboard/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityManageSlugRoute = CommunityManageSlugRouteImport.update({
  id: '/manage/$slug',
  path: '/manage/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityPaymentsSlugRoute = CommunityPaymentsSlugRouteImport.update({
  id: '/payments/$slug',
  path: '/payments/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityProfileSlugRoute = CommunityProfileSlugRouteImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayoutsRunRoute = ApiPublicPayoutsRunRouteImport.update({
  id: '/api/public/payouts/run',
  path: '/api/public/payouts/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushRemindersRoute = ApiPublicPushRemindersRouteImport.update({
  id: '/api/public/push/reminders',
  path: '/api/public/push/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answered': typeof AnsweredRoute
  '/bible': typeof BibleRoute
  '/campaign': typeof CampaignRoute
  '/care-agreement': typeof CareAgreementRoute
  '/circle': typeof CircleRoute
  '/community': typeof CommunityRouteWithChildren
  '/counselors': typeof CounselorsRouteWithChildren
  '/crisis': typeof CrisisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/giving': typeof GivingRouteWithChildren
  '/gratitude': typeof GratitudeRouteWithChildren
  '/help': typeof HelpRoute
  '/hire': typeof HireRoute
  '/hours': typeof HoursRoute
  '/journal': typeof JournalRoute
  '/kindness': typeof KindnessRoute
  '/lanes': typeof LanesRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/moderation': typeof ModerationRoute
  '/needs': typeof NeedsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/perks': typeof PerksRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room': typeof RoomRoute
  '/serve': typeof ServeRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spotlight': typeof SpotlightRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRouteWithChildren
  '/therapy': typeof TherapyRouteWithChildren
  '/tour': typeof TourRoute
  '/walk': typeof WalkRouteWithChildren
  '/wall': typeof WallRoute
  '/welcome': typeof WelcomeRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/gifts': typeof AdminGiftsRoute
  '/admin/grants': typeof AdminGrantsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/pros': typeof AdminProsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/badge/$id': typeof BadgeIdRoute
  '/call/$id': typeof CallIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/community/churches': typeof CommunityChurchesRoute
  '/community/new': typeof CommunityNewRoute
  '/counselor/$slug': typeof CounselorSlugRoute
  '/counselors/mine': typeof CounselorsMineRoute
  '/counselors/new': typeof CounselorsNewRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/film/$id': typeof FilmIdRoute
  '/film/queue': typeof FilmQueueRoute
  '/giving/$lane': typeof GivingLaneRoute
  '/giving/fund': typeof GivingFundRoute
  '/giving/nonprofits': typeof GivingNonprofitsRoute
  '/giving/witness': typeof GivingWitnessRoute
  '/gratitude/$id': typeof GratitudeIdRoute
  '/join/$slug': typeof JoinSlugRoute
  '/journey/$id': typeof JourneyIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/needs/$id': typeof NeedsIdRoute
  '/needs/new': typeof NeedsNewRoute
  '/needs/stories': typeof NeedsStoriesRoute
  '/person/$id': typeof PersonIdRoute
  '/prayer/$id': typeof PrayerIdRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pros/leads': typeof ProsLeadsRoute
  '/pros/mine': typeof ProsMineRoute
  '/pros/new': typeof ProsNewRoute
  '/pros/payments': typeof ProsPaymentsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/sit/$id': typeof SitIdRoute
  '/spaces/organization': typeof SpacesOrganizationRoute
  '/spaces/professional': typeof SpacesProfessionalRoute
  '/store/$slug': typeof StoreSlugRoute
  '/testimonials/share': typeof TestimonialsShareRoute
  '/therapy/$id': typeof TherapyIdRoute
  '/walk/$id': typeof WalkIdRoute
  '/community/': typeof CommunityIndexRoute
  '/counselors/': typeof CounselorsIndexRoute
  '/giving/': typeof GivingIndexRoute
  '/gratitude/': typeof GratitudeIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/needs/': typeof NeedsIndexRoute
  '/pros/': typeof ProsIndexRoute
  '/therapy/': typeof TherapyIndexRoute
  '/walk/': typeof WalkIndexRoute
  '/community/claim/$slug': typeof CommunityClaimSlugRoute
  '/community/dashboard/$slug': typeof CommunityDashboardSlugRoute
  '/community/manage/$slug': typeof CommunityManageSlugRoute
  '/community/payments/$slug': typeof CommunityPaymentsSlugRoute
  '/community/profile/$slug': typeof CommunityProfileSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/payouts/run': typeof ApiPublicPayoutsRunRoute
  '/api/public/push/reminders': typeof ApiPublicPushRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answered': typeof AnsweredRoute
  '/bible': typeof BibleRoute
  '/campaign': typeof CampaignRoute
  '/care-agreement': typeof CareAgreementRoute
  '/circle': typeof CircleRoute
  '/crisis': typeof CrisisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/hire': typeof HireRoute
  '/hours': typeof HoursRoute
  '/journal': typeof JournalRoute
  '/kindness': typeof KindnessRoute
  '/lanes': typeof LanesRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/perks': typeof PerksRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room': typeof RoomRoute
  '/serve': typeof ServeRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spotlight': typeof SpotlightRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRouteWithChildren
  '/tour': typeof TourRoute
  '/wall': typeof WallRoute
  '/welcome': typeof WelcomeRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/gifts': typeof AdminGiftsRoute
  '/admin/grants': typeof AdminGrantsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/pros': typeof AdminProsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/badge/$id': typeof BadgeIdRoute
  '/call/$id': typeof CallIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/community/churches': typeof CommunityChurchesRoute
  '/community/new': typeof CommunityNewRoute
  '/counselor/$slug': typeof CounselorSlugRoute
  '/counselors/mine': typeof CounselorsMineRoute
  '/counselors/new': typeof CounselorsNewRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/film/$id': typeof FilmIdRoute
  '/film/queue': typeof FilmQueueRoute
  '/giving/$lane': typeof GivingLaneRoute
  '/giving/fund': typeof GivingFundRoute
  '/giving/nonprofits': typeof GivingNonprofitsRoute
  '/giving/witness': typeof GivingWitnessRoute
  '/gratitude/$id': typeof GratitudeIdRoute
  '/join/$slug': typeof JoinSlugRoute
  '/journey/$id': typeof JourneyIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/needs/$id': typeof NeedsIdRoute
  '/needs/new': typeof NeedsNewRoute
  '/needs/stories': typeof NeedsStoriesRoute
  '/person/$id': typeof PersonIdRoute
  '/prayer/$id': typeof PrayerIdRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pros/leads': typeof ProsLeadsRoute
  '/pros/mine': typeof ProsMineRoute
  '/pros/new': typeof ProsNewRoute
  '/pros/payments': typeof ProsPaymentsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/sit/$id': typeof SitIdRoute
  '/spaces/organization': typeof SpacesOrganizationRoute
  '/spaces/professional': typeof SpacesProfessionalRoute
  '/store/$slug': typeof StoreSlugRoute
  '/testimonials/share': typeof TestimonialsShareRoute
  '/therapy/$id': typeof TherapyIdRoute
  '/walk/$id': typeof WalkIdRoute
  '/community': typeof CommunityIndexRoute
  '/counselors': typeof CounselorsIndexRoute
  '/giving': typeof GivingIndexRoute
  '/gratitude': typeof GratitudeIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/needs': typeof NeedsIndexRoute
  '/pros': typeof ProsIndexRoute
  '/therapy': typeof TherapyIndexRoute
  '/walk': typeof WalkIndexRoute
  '/community/claim/$slug': typeof CommunityClaimSlugRoute
  '/community/dashboard/$slug': typeof CommunityDashboardSlugRoute
  '/community/manage/$slug': typeof CommunityManageSlugRoute
  '/community/payments/$slug': typeof CommunityPaymentsSlugRoute
  '/community/profile/$slug': typeof CommunityProfileSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/payouts/run': typeof ApiPublicPayoutsRunRoute
  '/api/public/push/reminders': typeof ApiPublicPushRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answered': typeof AnsweredRoute
  '/bible': typeof BibleRoute
  '/campaign': typeof CampaignRoute
  '/care-agreement': typeof CareAgreementRoute
  '/circle': typeof CircleRoute
  '/community': typeof CommunityRouteWithChildren
  '/counselors': typeof CounselorsRouteWithChildren
  '/crisis': typeof CrisisRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/giving': typeof GivingRouteWithChildren
  '/gratitude': typeof GratitudeRouteWithChildren
  '/help': typeof HelpRoute
  '/hire': typeof HireRoute
  '/hours': typeof HoursRoute
  '/journal': typeof JournalRoute
  '/kindness': typeof KindnessRoute
  '/lanes': typeof LanesRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/moderation': typeof ModerationRoute
  '/needs': typeof NeedsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/perks': typeof PerksRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room': typeof RoomRoute
  '/serve': typeof ServeRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spotlight': typeof SpotlightRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRouteWithChildren
  '/therapy': typeof TherapyRouteWithChildren
  '/tour': typeof TourRoute
  '/walk': typeof WalkRouteWithChildren
  '/wall': typeof WallRoute
  '/welcome': typeof WelcomeRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/gifts': typeof AdminGiftsRoute
  '/admin/grants': typeof AdminGrantsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/pros': typeof AdminProsRoute
  '/admin/suggestions': typeof AdminSuggestionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/badge/$id': typeof BadgeIdRoute
  '/call/$id': typeof CallIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/community/churches': typeof CommunityChurchesRoute
  '/community/new': typeof CommunityNewRoute
  '/counselor/$slug': typeof CounselorSlugRoute
  '/counselors/mine': typeof CounselorsMineRoute
  '/counselors/new': typeof CounselorsNewRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/film/$id': typeof FilmIdRoute
  '/film/queue': typeof FilmQueueRoute
  '/giving/$lane': typeof GivingLaneRoute
  '/giving/fund': typeof GivingFundRoute
  '/giving/nonprofits': typeof GivingNonprofitsRoute
  '/giving/witness': typeof GivingWitnessRoute
  '/gratitude/$id': typeof GratitudeIdRoute
  '/join/$slug': typeof JoinSlugRoute
  '/journey/$id': typeof JourneyIdRoute
  '/messages/$id': typeof MessagesIdRoute
  '/needs/$id': typeof NeedsIdRoute
  '/needs/new': typeof NeedsNewRoute
  '/needs/stories': typeof NeedsStoriesRoute
  '/person/$id': typeof PersonIdRoute
  '/prayer/$id': typeof PrayerIdRoute
  '/pro/$slug': typeof ProSlugRoute
  '/pros/leads': typeof ProsLeadsRoute
  '/pros/mine': typeof ProsMineRoute
  '/pros/new': typeof ProsNewRoute
  '/pros/payments': typeof ProsPaymentsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/sit/$id': typeof SitIdRoute
  '/spaces/organization': typeof SpacesOrganizationRoute
  '/spaces/professional': typeof SpacesProfessionalRoute
  '/store/$slug': typeof StoreSlugRoute
  '/testimonials/share': typeof TestimonialsShareRoute
  '/therapy/$id': typeof TherapyIdRoute
  '/walk/$id': typeof WalkIdRoute
  '/community/': typeof CommunityIndexRoute
  '/counselors/': typeof CounselorsIndexRoute
  '/giving/': typeof GivingIndexRoute
  '/gratitude/': typeof GratitudeIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/needs/': typeof NeedsIndexRoute
  '/pros/': typeof ProsIndexRoute
  '/therapy/': typeof TherapyIndexRoute
  '/walk/': typeof WalkIndexRoute
  '/community/claim/$slug': typeof CommunityClaimSlugRoute
  '/community/dashboard/$slug': typeof CommunityDashboardSlugRoute
  '/community/manage/$slug': typeof CommunityManageSlugRoute
  '/community/payments/$slug': typeof CommunityPaymentsSlugRoute
  '/community/profile/$slug': typeof CommunityProfileSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/payouts/run': typeof ApiPublicPayoutsRunRoute
  '/api/public/push/reminders': typeof ApiPublicPushRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answered'
    | '/bible'
    | '/campaign'
    | '/care-agreement'
    | '/circle'
    | '/community'
    | '/counselors'
    | '/crisis'
    | '/forgot-password'
    | '/get-started'
    | '/giving'
    | '/gratitude'
    | '/help'
    | '/hire'
    | '/hours'
    | '/journal'
    | '/kindness'
    | '/lanes'
    | '/ledger'
    | '/login'
    | '/map'
    | '/moderation'
    | '/needs'
    | '/notifications'
    | '/perks'
    | '/privacy'
    | '/profile'
    | '/record'
    | '/reset-password'
    | '/room'
    | '/serve'
    | '/setup'
    | '/sitemap.xml'
    | '/spotlight'
    | '/start'
    | '/terms'
    | '/testimonials'
    | '/therapy'
    | '/tour'
    | '/walk'
    | '/wall'
    | '/welcome'
    | '/admin/claims'
    | '/admin/counselors'
    | '/admin/gifts'
    | '/admin/grants'
    | '/admin/invites'
    | '/admin/pros'
    | '/admin/suggestions'
    | '/admin/support'
    | '/admin/testimonials'
    | '/badge/$id'
    | '/call/$id'
    | '/checkout/return'
    | '/community/$slug'
    | '/community/churches'
    | '/community/new'
    | '/counselor/$slug'
    | '/counselors/mine'
    | '/counselors/new'
    | '/donate/$slug'
    | '/film/$id'
    | '/film/queue'
    | '/giving/$lane'
    | '/giving/fund'
    | '/giving/nonprofits'
    | '/giving/witness'
    | '/gratitude/$id'
    | '/join/$slug'
    | '/journey/$id'
    | '/messages/$id'
    | '/needs/$id'
    | '/needs/new'
    | '/needs/stories'
    | '/person/$id'
    | '/prayer/$id'
    | '/pro/$slug'
    | '/pros/leads'
    | '/pros/mine'
    | '/pros/new'
    | '/pros/payments'
    | '/requests/$id'
    | '/sit/$id'
    | '/spaces/organization'
    | '/spaces/professional'
    | '/store/$slug'
    | '/testimonials/share'
    | '/therapy/$id'
    | '/walk/$id'
    | '/community/'
    | '/counselors/'
    | '/giving/'
    | '/gratitude/'
    | '/messages/'
    | '/needs/'
    | '/pros/'
    | '/therapy/'
    | '/walk/'
    | '/community/claim/$slug'
    | '/community/dashboard/$slug'
    | '/community/manage/$slug'
    | '/community/payments/$slug'
    | '/community/profile/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/payouts/run'
    | '/api/public/push/reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answered'
    | '/bible'
    | '/campaign'
    | '/care-agreement'
    | '/circle'
    | '/crisis'
    | '/forgot-password'
    | '/get-started'
    | '/help'
    | '/hire'
    | '/hours'
    | '/journal'
    | '/kindness'
    | '/lanes'
    | '/ledger'
    | '/login'
    | '/map'
    | '/moderation'
    | '/notifications'
    | '/perks'
    | '/privacy'
    | '/profile'
    | '/record'
    | '/reset-password'
    | '/room'
    | '/serve'
    | '/setup'
    | '/sitemap.xml'
    | '/spotlight'
    | '/start'
    | '/terms'
    | '/testimonials'
    | '/tour'
    | '/wall'
    | '/welcome'
    | '/admin/claims'
    | '/admin/counselors'
    | '/admin/gifts'
    | '/admin/grants'
    | '/admin/invites'
    | '/admin/pros'
    | '/admin/suggestions'
    | '/admin/support'
    | '/admin/testimonials'
    | '/badge/$id'
    | '/call/$id'
    | '/checkout/return'
    | '/community/$slug'
    | '/community/churches'
    | '/community/new'
    | '/counselor/$slug'
    | '/counselors/mine'
    | '/counselors/new'
    | '/donate/$slug'
    | '/film/$id'
    | '/film/queue'
    | '/giving/$lane'
    | '/giving/fund'
    | '/giving/nonprofits'
    | '/giving/witness'
    | '/gratitude/$id'
    | '/join/$slug'
    | '/journey/$id'
    | '/messages/$id'
    | '/needs/$id'
    | '/needs/new'
    | '/needs/stories'
    | '/person/$id'
    | '/prayer/$id'
    | '/pro/$slug'
    | '/pros/leads'
    | '/pros/mine'
    | '/pros/new'
    | '/pros/payments'
    | '/requests/$id'
    | '/sit/$id'
    | '/spaces/organization'
    | '/spaces/professional'
    | '/store/$slug'
    | '/testimonials/share'
    | '/therapy/$id'
    | '/walk/$id'
    | '/community'
    | '/counselors'
    | '/giving'
    | '/gratitude'
    | '/messages'
    | '/needs'
    | '/pros'
    | '/therapy'
    | '/walk'
    | '/community/claim/$slug'
    | '/community/dashboard/$slug'
    | '/community/manage/$slug'
    | '/community/payments/$slug'
    | '/community/profile/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/payouts/run'
    | '/api/public/push/reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/answered'
    | '/bible'
    | '/campaign'
    | '/care-agreement'
    | '/circle'
    | '/community'
    | '/counselors'
    | '/crisis'
    | '/forgot-password'
    | '/get-started'
    | '/giving'
    | '/gratitude'
    | '/help'
    | '/hire'
    | '/hours'
    | '/journal'
    | '/kindness'
    | '/lanes'
    | '/ledger'
    | '/login'
    | '/map'
    | '/moderation'
    | '/needs'
    | '/notifications'
    | '/perks'
    | '/privacy'
    | '/profile'
    | '/record'
    | '/reset-password'
    | '/room'
    | '/serve'
    | '/setup'
    | '/sitemap.xml'
    | '/spotlight'
    | '/start'
    | '/terms'
    | '/testimonials'
    | '/therapy'
    | '/tour'
    | '/walk'
    | '/wall'
    | '/welcome'
    | '/admin/claims'
    | '/admin/counselors'
    | '/admin/gifts'
    | '/admin/grants'
    | '/admin/invites'
    | '/admin/pros'
    | '/admin/suggestions'
    | '/admin/support'
    | '/admin/testimonials'
    | '/badge/$id'
    | '/call/$id'
    | '/checkout/return'
    | '/community/$slug'
    | '/community/churches'
    | '/community/new'
    | '/counselor/$slug'
    | '/counselors/mine'
    | '/counselors/new'
    | '/donate/$slug'
    | '/film/$id'
    | '/film/queue'
    | '/giving/$lane'
    | '/giving/fund'
    | '/giving/nonprofits'
    | '/giving/witness'
    | '/gratitude/$id'
    | '/join/$slug'
    | '/journey/$id'
    | '/messages/$id'
    | '/needs/$id'
    | '/needs/new'
    | '/needs/stories'
    | '/person/$id'
    | '/prayer/$id'
    | '/pro/$slug'
    | '/pros/leads'
    | '/pros/mine'
    | '/pros/new'
    | '/pros/payments'
    | '/requests/$id'
    | '/sit/$id'
    | '/spaces/organization'
    | '/spaces/professional'
    | '/store/$slug'
    | '/testimonials/share'
    | '/therapy/$id'
    | '/walk/$id'
    | '/community/'
    | '/counselors/'
    | '/giving/'
    | '/gratitude/'
    | '/messages/'
    | '/needs/'
    | '/pros/'
    | '/therapy/'
    | '/walk/'
    | '/community/claim/$slug'
    | '/community/dashboard/$slug'
    | '/community/manage/$slug'
    | '/community/payments/$slug'
    | '/community/profile/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/payouts/run'
    | '/api/public/push/reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnsweredRoute: typeof AnsweredRoute
  BibleRoute: typeof BibleRoute
  CampaignRoute: typeof CampaignRoute
  CareAgreementRoute: typeof CareAgreementRoute
  CircleRoute: typeof CircleRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  CounselorsRoute: typeof CounselorsRouteWithChildren
  CrisisRoute: typeof CrisisRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetStartedRoute: typeof GetStartedRoute
  GivingRoute: typeof GivingRouteWithChildren
  GratitudeRoute: typeof GratitudeRouteWithChildren
  HelpRoute: typeof HelpRoute
  HireRoute: typeof HireRoute
  HoursRoute: typeof HoursRoute
  JournalRoute: typeof JournalRoute
  KindnessRoute: typeof KindnessRoute
  LanesRoute: typeof LanesRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ModerationRoute: typeof ModerationRoute
  NeedsRoute: typeof NeedsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PerksRoute: typeof PerksRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomRoute: typeof RoomRoute
  ServeRoute: typeof ServeRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpotlightRoute: typeof SpotlightRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRouteWithChildren
  TherapyRoute: typeof TherapyRouteWithChildren
  TourRoute: typeof TourRoute
  WalkRoute: typeof WalkRouteWithChildren
  WallRoute: typeof WallRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminCounselorsRoute: typeof AdminCounselorsRoute
  AdminGiftsRoute: typeof AdminGiftsRoute
  AdminGrantsRoute: typeof AdminGrantsRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminProsRoute: typeof AdminProsRoute
  AdminSuggestionsRoute: typeof AdminSuggestionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  BadgeIdRoute: typeof BadgeIdRoute
  CallIdRoute: typeof CallIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CounselorSlugRoute: typeof CounselorSlugRoute
  DonateSlugRoute: typeof DonateSlugRoute
  FilmIdRoute: typeof FilmIdRoute
  FilmQueueRoute: typeof FilmQueueRoute
  JoinSlugRoute: typeof JoinSlugRoute
  JourneyIdRoute: typeof JourneyIdRoute
  MessagesIdRoute: typeof MessagesIdRoute
  PersonIdRoute: typeof PersonIdRoute
  PrayerIdRoute: typeof PrayerIdRoute
  ProSlugRoute: typeof ProSlugRoute
  ProsLeadsRoute: typeof ProsLeadsRoute
  ProsMineRoute: typeof ProsMineRoute
  ProsNewRoute: typeof ProsNewRoute
  ProsPaymentsRoute: typeof ProsPaymentsRoute
  RequestsIdRoute: typeof RequestsIdRoute
  SitIdRoute: typeof SitIdRoute
  SpacesOrganizationRoute: typeof SpacesOrganizationRoute
  SpacesProfessionalRoute: typeof SpacesProfessionalRoute
  StoreSlugRoute: typeof StoreSlugRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ProsIndexRoute: typeof ProsIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPayoutsRunRoute: typeof ApiPublicPayoutsRunRoute
  ApiPublicPushRemindersRoute: typeof ApiPublicPushRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answered': {
      id: '/answered'
      path: '/answered'
      fullPath: '/answered'
      preLoaderRoute: typeof AnsweredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-agreement': {
      id: '/care-agreement'
      path: '/care-agreement'
      fullPath: '/care-agreement'
      preLoaderRoute: typeof CareAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselors': {
      id: '/counselors'
      path: '/counselors'
      fullPath: '/counselors'
      preLoaderRoute: typeof CounselorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving': {
      id: '/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof GivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours': {
      id: '/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kindness': {
      id: '/kindness'
      path: '/kindness'
      fullPath: '/kindness'
      preLoaderRoute: typeof KindnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes': {
      id: '/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof LanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs': {
      id: '/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof NeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve': {
      id: '/serve'
      path: '/serve'
      fullPath: '/serve'
      preLoaderRoute: typeof ServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlight': {
      id: '/spotlight'
      path: '/spotlight'
      fullPath: '/spotlight'
      preLoaderRoute: typeof SpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapy': {
      id: '/therapy'
      path: '/therapy'
      fullPath: '/therapy'
      preLoaderRoute: typeof TherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/counselors': {
      id: '/admin/counselors'
      path: '/admin/counselors'
      fullPath: '/admin/counselors'
      preLoaderRoute: typeof AdminCounselorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gifts': {
      id: '/admin/gifts'
      path: '/admin/gifts'
      fullPath: '/admin/gifts'
      preLoaderRoute: typeof AdminGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/grants': {
      id: '/admin/grants'
      path: '/admin/grants'
      fullPath: '/admin/grants'
      preLoaderRoute: typeof AdminGrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pros': {
      id: '/admin/pros'
      path: '/admin/pros'
      fullPath: '/admin/pros'
      preLoaderRoute: typeof AdminProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suggestions': {
      id: '/admin/suggestions'
      path: '/admin/suggestions'
      fullPath: '/admin/suggestions'
      preLoaderRoute: typeof AdminSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/$id': {
      id: '/badge/$id'
      path: '/badge/$id'
      fullPath: '/badge/$id'
      preLoaderRoute: typeof BadgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$id': {
      id: '/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof CallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/churches': {
      id: '/community/churches'
      path: '/churches'
      fullPath: '/community/churches'
      preLoaderRoute: typeof CommunityChurchesRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/new': {
      id: '/community/new'
      path: '/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof CommunityNewRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/counselor/$slug': {
      id: '/counselor/$slug'
      path: '/counselor/$slug'
      fullPath: '/counselor/$slug'
      preLoaderRoute: typeof CounselorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselors/': {
      id: '/counselors/'
      path: '/'
      fullPath: '/counselors/'
      preLoaderRoute: typeof CounselorsIndexRouteImport
      parentRoute: typeof CounselorsRoute
    }
    '/counselors/mine': {
      id: '/counselors/mine'
      path: '/mine'
      fullPath: '/counselors/mine'
      preLoaderRoute: typeof CounselorsMineRouteImport
      parentRoute: typeof CounselorsRoute
    }
    '/counselors/new': {
      id: '/counselors/new'
      path: '/new'
      fullPath: '/counselors/new'
      preLoaderRoute: typeof CounselorsNewRouteImport
      parentRoute: typeof CounselorsRoute
    }
    '/donate/$slug': {
      id: '/donate/$slug'
      path: '/donate/$slug'
      fullPath: '/donate/$slug'
      preLoaderRoute: typeof DonateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/queue': {
      id: '/film/queue'
      path: '/film/queue'
      fullPath: '/film/queue'
      preLoaderRoute: typeof FilmQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giving/': {
      id: '/giving/'
      path: '/'
      fullPath: '/giving/'
      preLoaderRoute: typeof GivingIndexRouteImport
      parentRoute: typeof GivingRoute
    }
    '/giving/$lane': {
      id: '/giving/$lane'
      path: '/$lane'
      fullPath: '/giving/$lane'
      preLoaderRoute: typeof GivingLaneRouteImport
      parentRoute: typeof GivingRoute
    }
    '/giving/fund': {
      id: '/giving/fund'
      path: '/fund'
      fullPath: '/giving/fund'
      preLoaderRoute: typeof GivingFundRouteImport
      parentRoute: typeof GivingRoute
    }
    '/giving/nonprofits': {
      id: '/giving/nonprofits'
      path: '/nonprofits'
      fullPath: '/giving/nonprofits'
      preLoaderRoute: typeof GivingNonprofitsRouteImport
      parentRoute: typeof GivingRoute
    }
    '/giving/witness': {
      id: '/giving/witness'
      path: '/witness'
      fullPath: '/giving/witness'
      preLoaderRoute: typeof GivingWitnessRouteImport
      parentRoute: typeof GivingRoute
    }
    '/gratitude/': {
      id: '/gratitude/'
      path: '/'
      fullPath: '/gratitude/'
      preLoaderRoute: typeof GratitudeIndexRouteImport
      parentRoute: typeof GratitudeRoute
    }
    '/gratitude/$id': {
      id: '/gratitude/$id'
      path: '/$id'
      fullPath: '/gratitude/$id'
      preLoaderRoute: typeof GratitudeIdRouteImport
      parentRoute: typeof GratitudeRoute
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$id': {
      id: '/journey/$id'
      path: '/journey/$id'
      fullPath: '/journey/$id'
      preLoaderRoute: typeof JourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs/': {
      id: '/needs/'
      path: '/'
      fullPath: '/needs/'
      preLoaderRoute: typeof NeedsIndexRouteImport
      parentRoute: typeof NeedsRoute
    }
    '/needs/$id': {
      id: '/needs/$id'
      path: '/$id'
      fullPath: '/needs/$id'
      preLoaderRoute: typeof NeedsIdRouteImport
      parentRoute: typeof NeedsRoute
    }
    '/needs/new': {
      id: '/needs/new'
      path: '/new'
      fullPath: '/needs/new'
      preLoaderRoute: typeof NeedsNewRouteImport
      parentRoute: typeof NeedsRoute
    }
    '/needs/stories': {
      id: '/needs/stories'
      path: '/stories'
      fullPath: '/needs/stories'
      preLoaderRoute: typeof NeedsStoriesRouteImport
      parentRoute: typeof NeedsRoute
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer/$id': {
      id: '/prayer/$id'
      path: '/prayer/$id'
      fullPath: '/prayer/$id'
      preLoaderRoute: typeof PrayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$slug': {
      id: '/pro/$slug'
      path: '/pro/$slug'
      fullPath: '/pro/$slug'
      preLoaderRoute: typeof ProSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/': {
      id: '/pros/'
      path: '/pros'
      fullPath: '/pros/'
      preLoaderRoute: typeof ProsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/leads': {
      id: '/pros/leads'
      path: '/pros/leads'
      fullPath: '/pros/leads'
      preLoaderRoute: typeof ProsLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/mine': {
      id: '/pros/mine'
      path: '/pros/mine'
      fullPath: '/pros/mine'
      preLoaderRoute: typeof ProsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/new': {
      id: '/pros/new'
      path: '/pros/new'
      fullPath: '/pros/new'
      preLoaderRoute: typeof ProsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/payments': {
      id: '/pros/payments'
      path: '/pros/payments'
      fullPath: '/pros/payments'
      preLoaderRoute: typeof ProsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sit/$id': {
      id: '/sit/$id'
      path: '/sit/$id'
      fullPath: '/sit/$id'
      preLoaderRoute: typeof SitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/organization': {
      id: '/spaces/organization'
      path: '/spaces/organization'
      fullPath: '/spaces/organization'
      preLoaderRoute: typeof SpacesOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/professional': {
      id: '/spaces/professional'
      path: '/spaces/professional'
      fullPath: '/spaces/professional'
      preLoaderRoute: typeof SpacesProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/share': {
      id: '/testimonials/share'
      path: '/share'
      fullPath: '/testimonials/share'
      preLoaderRoute: typeof TestimonialsShareRouteImport
      parentRoute: typeof TestimonialsRoute
    }
    '/therapy/': {
      id: '/therapy/'
      path: '/'
      fullPath: '/therapy/'
      preLoaderRoute: typeof TherapyIndexRouteImport
      parentRoute: typeof TherapyRoute
    }
    '/therapy/$id': {
      id: '/therapy/$id'
      path: '/$id'
      fullPath: '/therapy/$id'
      preLoaderRoute: typeof TherapyIdRouteImport
      parentRoute: typeof TherapyRoute
    }
    '/walk/': {
      id: '/walk/'
      path: '/'
      fullPath: '/walk/'
      preLoaderRoute: typeof WalkIndexRouteImport
      parentRoute: typeof WalkRoute
    }
    '/walk/$id': {
      id: '/walk/$id'
      path: '/$id'
      fullPath: '/walk/$id'
      preLoaderRoute: typeof WalkIdRouteImport
      parentRoute: typeof WalkRoute
    }
    '/community/claim/$slug': {
      id: '/community/claim/$slug'
      path: '/claim/$slug'
      fullPath: '/community/claim/$slug'
      preLoaderRoute: typeof CommunityClaimSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/dashboard/$slug': {
      id: '/community/dashboard/$slug'
      path: '/dashboard/$slug'
      fullPath: '/community/dashboard/$slug'
      preLoaderRoute: typeof CommunityDashboardSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/manage/$slug': {
      id: '/community/manage/$slug'
      path: '/manage/$slug'
      fullPath: '/community/manage/$slug'
      preLoaderRoute: typeof CommunityManageSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/payments/$slug': {
      id: '/community/payments/$slug'
      path: '/payments/$slug'
      fullPath: '/community/payments/$slug'
      preLoaderRoute: typeof CommunityPaymentsSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/profile/$slug': {
      id: '/community/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/community/profile/$slug'
      preLoaderRoute: typeof CommunityProfileSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payouts/run': {
      id: '/api/public/payouts/run'
      path: '/api/public/payouts/run'
      fullPath: '/api/public/payouts/run'
      preLoaderRoute: typeof ApiPublicPayoutsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/reminders': {
      id: '/api/public/push/reminders'
      path: '/api/public/push/reminders'
      fullPath: '/api/public/push/reminders'
      preLoaderRoute: typeof ApiPublicPushRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunityRouteChildren {
  CommunitySlugRoute: typeof CommunitySlugRoute
  CommunityChurchesRoute: typeof CommunityChurchesRoute
  CommunityNewRoute: typeof CommunityNewRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityClaimSlugRoute: typeof CommunityClaimSlugRoute
  CommunityDashboardSlugRoute: typeof CommunityDashboardSlugRoute
  CommunityManageSlugRoute: typeof CommunityManageSlugRoute
  CommunityPaymentsSlugRoute: typeof CommunityPaymentsSlugRoute
  CommunityProfileSlugRoute: typeof CommunityProfileSlugRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunitySlugRoute: CommunitySlugRoute,
  CommunityChurchesRoute: CommunityChurchesRoute,
  CommunityNewRoute: CommunityNewRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityClaimSlugRoute: CommunityClaimSlugRoute,
  CommunityDashboardSlugRoute: CommunityDashboardSlugRoute,
  CommunityManageSlugRoute: CommunityManageSlugRoute,
  CommunityPaymentsSlugRoute: CommunityPaymentsSlugRoute,
  CommunityProfileSlugRoute: CommunityProfileSlugRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface CounselorsRouteChildren {
  CounselorsMineRoute: typeof CounselorsMineRoute
  CounselorsNewRoute: typeof CounselorsNewRoute
  CounselorsIndexRoute: typeof CounselorsIndexRoute
}

const CounselorsRouteChildren: CounselorsRouteChildren = {
  CounselorsMineRoute: CounselorsMineRoute,
  CounselorsNewRoute: CounselorsNewRoute,
  CounselorsIndexRoute: CounselorsIndexRoute,
}

const CounselorsRouteWithChildren = CounselorsRoute._addFileChildren(
  CounselorsRouteChildren,
)

interface GivingRouteChildren {
  GivingLaneRoute: typeof GivingLaneRoute
  GivingFundRoute: typeof GivingFundRoute
  GivingNonprofitsRoute: typeof GivingNonprofitsRoute
  GivingWitnessRoute: typeof GivingWitnessRoute
  GivingIndexRoute: typeof GivingIndexRoute
}

const GivingRouteChildren: GivingRouteChildren = {
  GivingLaneRoute: GivingLaneRoute,
  GivingFundRoute: GivingFundRoute,
  GivingNonprofitsRoute: GivingNonprofitsRoute,
  GivingWitnessRoute: GivingWitnessRoute,
  GivingIndexRoute: GivingIndexRoute,
}

const GivingRouteWithChildren =
  GivingRoute._addFileChildren(GivingRouteChildren)

interface GratitudeRouteChildren {
  GratitudeIdRoute: typeof GratitudeIdRoute
  GratitudeIndexRoute: typeof GratitudeIndexRoute
}

const GratitudeRouteChildren: GratitudeRouteChildren = {
  GratitudeIdRoute: GratitudeIdRoute,
  GratitudeIndexRoute: GratitudeIndexRoute,
}

const GratitudeRouteWithChildren = GratitudeRoute._addFileChildren(
  GratitudeRouteChildren,
)

interface NeedsRouteChildren {
  NeedsIdRoute: typeof NeedsIdRoute
  NeedsNewRoute: typeof NeedsNewRoute
  NeedsStoriesRoute: typeof NeedsStoriesRoute
  NeedsIndexRoute: typeof NeedsIndexRoute
}

const NeedsRouteChildren: NeedsRouteChildren = {
  NeedsIdRoute: NeedsIdRoute,
  NeedsNewRoute: NeedsNewRoute,
  NeedsStoriesRoute: NeedsStoriesRoute,
  NeedsIndexRoute: NeedsIndexRoute,
}

const NeedsRouteWithChildren = NeedsRoute._addFileChildren(NeedsRouteChildren)

interface TestimonialsRouteChildren {
  TestimonialsShareRoute: typeof TestimonialsShareRoute
}

const TestimonialsRouteChildren: TestimonialsRouteChildren = {
  TestimonialsShareRoute: TestimonialsShareRoute,
}

const TestimonialsRouteWithChildren = TestimonialsRoute._addFileChildren(
  TestimonialsRouteChildren,
)

interface TherapyRouteChildren {
  TherapyIdRoute: typeof TherapyIdRoute
  TherapyIndexRoute: typeof TherapyIndexRoute
}

const TherapyRouteChildren: TherapyRouteChildren = {
  TherapyIdRoute: TherapyIdRoute,
  TherapyIndexRoute: TherapyIndexRoute,
}

const TherapyRouteWithChildren =
  TherapyRoute._addFileChildren(TherapyRouteChildren)

interface WalkRouteChildren {
  WalkIdRoute: typeof WalkIdRoute
  WalkIndexRoute: typeof WalkIndexRoute
}

const WalkRouteChildren: WalkRouteChildren = {
  WalkIdRoute: WalkIdRoute,
  WalkIndexRoute: WalkIndexRoute,
}

const WalkRouteWithChildren = WalkRoute._addFileChildren(WalkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnsweredRoute: AnsweredRoute,
  BibleRoute: BibleRoute,
  CampaignRoute: CampaignRoute,
  CareAgreementRoute: CareAgreementRoute,
  CircleRoute: CircleRoute,
  CommunityRoute: CommunityRouteWithChildren,
  CounselorsRoute: CounselorsRouteWithChildren,
  CrisisRoute: CrisisRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetStartedRoute: GetStartedRoute,
  GivingRoute: GivingRouteWithChildren,
  GratitudeRoute: GratitudeRouteWithChildren,
  HelpRoute: HelpRoute,
  HireRoute: HireRoute,
  HoursRoute: HoursRoute,
  JournalRoute: JournalRoute,
  KindnessRoute: KindnessRoute,
  LanesRoute: LanesRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ModerationRoute: ModerationRoute,
  NeedsRoute: NeedsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PerksRoute: PerksRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomRoute: RoomRoute,
  ServeRoute: ServeRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpotlightRoute: SpotlightRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRouteWithChildren,
  TherapyRoute: TherapyRouteWithChildren,
  TourRoute: TourRoute,
  WalkRoute: WalkRouteWithChildren,
  WallRoute: WallRoute,
  WelcomeRoute: WelcomeRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminCounselorsRoute: AdminCounselorsRoute,
  AdminGiftsRoute: AdminGiftsRoute,
  AdminGrantsRoute: AdminGrantsRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminProsRoute: AdminProsRoute,
  AdminSuggestionsRoute: AdminSuggestionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  BadgeIdRoute: BadgeIdRoute,
  CallIdRoute: CallIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CounselorSlugRoute: CounselorSlugRoute,
  DonateSlugRoute: DonateSlugRoute,
  FilmIdRoute: FilmIdRoute,
  FilmQueueRoute: FilmQueueRoute,
  JoinSlugRoute: JoinSlugRoute,
  JourneyIdRoute: JourneyIdRoute,
  MessagesIdRoute: MessagesIdRoute,
  PersonIdRoute: PersonIdRoute,
  PrayerIdRoute: PrayerIdRoute,
  ProSlugRoute: ProSlugRoute,
  ProsLeadsRoute: ProsLeadsRoute,
  ProsMineRoute: ProsMineRoute,
  ProsNewRoute: ProsNewRoute,
  ProsPaymentsRoute: ProsPaymentsRoute,
  RequestsIdRoute: RequestsIdRoute,
  SitIdRoute: SitIdRoute,
  SpacesOrganizationRoute: SpacesOrganizationRoute,
  SpacesProfessionalRoute: SpacesProfessionalRoute,
  StoreSlugRoute: StoreSlugRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ProsIndexRoute: ProsIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPayoutsRunRoute: ApiPublicPayoutsRunRoute,
  ApiPublicPushRemindersRoute: ApiPublicPushRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
